

MARKETCOREMANAGER_IP = "192.168.0.180"
MARKETCOREMANAGER_ID = 1 

INTERFACECOMMON = "<iii"

#-----------------------------------------------
# OnGui Parameters
ONGUI_PORT = 3000
ONGUI_ID = 17
ONGUI_REQ1_ID = 1
ONGUI_REQ2_ID = 2
ONGUI_RECV1_ID = 1
ONGUI_RECV2_ID = 2
ONGUI_RECV3_ID = 3
ONGUI_RECV4_ID = 4

# USER ID
ONGUI_REQ1 = "i"
# USER ORDER LIST
ONGUI_REQ2 = "i"+"i"*16+"?"
# USER ID CONFIRMED
ONGUI_RECV1 = "?"
# MARKET ITEM LIST
ONGUI_RECV2 = "i"+"i"*16
# USER ORDER CONFIRMED
ONGUI_RECV3 = "?"
# USER ORDER STATUS
ONGUI_RECV4 = "ii"

#-----------------------------------------------
# AdminGui Parameters
ADMINGUI_PORT = 3001
ADMINGUI_ID = 18
ADMINGUI_REQ1_ID = 1
ADMINGUI_REQ2_ID = 2
ADMINGUI_RECV1_ID = 101
ADMINGUI_RECV2_ID = 102
ADMINGUI_RECV3_ID = 103

# ADMIN ID
ADMINGUI_REQ1 = "i"
# UPDATE MARKET ITEM LIST
ADMINGUI_REQ2 = "i"+"i"*16
# USER ID CONFIRMED
ADMINGUI_RECV1 = "?"
# MARKET ITEM LIST
ADMINGUI_RECV2 = "i"+"i"*16
# CART STATUS
ADMINGUI_RECV3 = "iiifff"

#-----------------------------------------------
