
CARTSTATEMANAGER_IP = "192.168.0.180"
CARTSTATEMANAGER_ID = 33 

CARTSTATEMANAGER_FUNCTION1_ID = 1
CARTSTATEMANAGER_FUNCTION101_ID = 101

INTERFACECOMMON = "<iii"
#INTERFACEMANAGER STATE UPDATE
CARTSTATEMANAGER_FUNCTION_1 = "i"
#PERCEPTIONMANAGER STATE UPDATE
CARTSTATEMANAGER_FUNCTION_101 = "i"

# InterfaceManager Parameters
#-----------------------------------------------
INTERFACEMANAGER_PORT = 6000
INTERFACEMANAGER_ID = 35
INTERFACEMANAGER_FUNCTION1_ID = 1
INTERFACEMANAGER_FUNCTION2_ID = 2

# USER COMMAND INPUT
INTERFACEMANAGER_FUNCTION_1 = "i"
INTERFACEMANAGER_FUNCTION_2 = "ii"

#-----------------------------------------------
# PerceptionManager Parameters
PERCEPTIONMANAGER_PORT = 6001
PERCEPTIONMANAGER_ID = 34
PERCEPTIONMANAGER_FUNCTION_ID = 1
PERCEPTIONMANAGER_FUNCTION_ID = 2

# USER REGISTER CONFIRMED
PERCEPTIONMANAGER_FUNCTION_1 = "?"
# USER COMMAND INPUT
PERCEPTIONMANAGER_FUNCTION_2 = "iii"+"fff"

#-----------------------------------------------
